name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          tags: tenma/music_download_web:latest
          outputs: type=docker,dest=music_download_web_arm64_latest.tar

      - name: Build Docker image for amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: tenma/music_download_web:latest
          outputs: type=docker,dest=music_download_web_amd64_latest.tar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            music_download_web_arm64_latest.tar
            music_download_web_amd64_latest.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
